services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  sql:
    container_name: "sql"
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Znng7j3ORPTvgHAhf00m6e"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "sql"
    volumes:
    - "authservice-sqldata:/var/opt/mssql"
    ports:
    - target: 1433
      published: 1433
    restart: unless-stopped
  auth-migrations:
    container_name: "auth-migrations"
    image: "auth-migrations:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__authdb: "Server=sql,1433;User ID=sa;Password=Znng7j3ORPTvgHAhf00m6e;TrustServerCertificate=true;Initial Catalog=authdb"
      AUTHDB_HOST: "sql"
      AUTHDB_PORT: "1433"
      AUTHDB_USERNAME: "sa"
      AUTHDB_PASSWORD: "Znng7j3ORPTvgHAhf00m6e"
      AUTHDB_URI: "mssql://sa:Znng7j3ORPTvgHAhf00m6e@sql:1433/authdb"
      AUTHDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sql:1433;trustServerCertificate=true;databaseName=authdb"
      AUTHDB_DATABASENAME: "authdb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "auth-migrations"
    restart: unless-stopped
  authservice:
    container_name: "authservice"
    image: "authservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__authdb: "Server=sql,1433;User ID=sa;Password=Znng7j3ORPTvgHAhf00m6e;TrustServerCertificate=true;Initial Catalog=authdb"
      AUTHDB_HOST: "sql"
      AUTHDB_PORT: "1433"
      AUTHDB_USERNAME: "sa"
      AUTHDB_PASSWORD: "Znng7j3ORPTvgHAhf00m6e"
      AUTHDB_URI: "mssql://sa:Znng7j3ORPTvgHAhf00m6e@sql:1433/authdb"
      AUTHDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sql:1433;trustServerCertificate=true;databaseName=authdb"
      AUTHDB_DATABASENAME: "authdb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "authservice"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  apigateway:
    container_name: "apigateway"
    image: "apigateway:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      AUTHSERVICE_HTTP: "http://authservice:8080"
      services__authservice__http__0: "http://authservice:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "apigateway"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  frontend:
    container_name: "frontend"
    build:
      context: ../..
      dockerfile: ProjetWeb.Frontend/Dockerfile
    environment:
      NODE_ENV: "development"
      APIGATEWAY_HTTP: "http://apigateway:8080"
      services__apigateway__http__0: "http://apigateway:8080"
      PORT: "8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "frontend"
    ports:
    - target: 8000
      published: 8000
    restart: unless-stopped
volumes:
  authservice-sqldata: {}
